---
apiVersion: shulkermc.io/v1alpha1
kind: MinecraftCluster
metadata:
  name: minecraft
  namespace: apps
spec:
  networkAdmins:
    - 88031478-2813-43cf-bc19-9fd22b078d74
---
apiVersion: shulkermc.io/v1alpha1
kind: ProxyFleet
metadata:
  name: minecraft
  namespace: apps
spec:
  clusterRef:
    name: minecraft
  replicas: 1
  service:
    externalTrafficPolicy: Local
    type: NodePort
  template:
    spec:
      version:
        channel: Velocity
        name: latest
      config: {}