---
apiVersion: shulkermc.io/v1alpha1
kind: MinecraftCluster
metadata:
  name: minecraft-cluster
  namespace: apps
spec:
  networkAdmins:
    - 88031478-2813-43cf-bc19-9fd22b078d74
---
apiVersion: shulkermc.io/v1alpha1
kind: ProxyFleet
metadata:
  name: minecraft-proxy
  namespace: apps
spec:
  clusterRef:
    name: minecraft-cluster
  replicas: 1
  service:
    type: ClusterIP
  template:
    spec:
      version:
        channel: Velocity
        name: latest
      config: {}
---
apiVersion: shulkermc.io/v1alpha1
kind: MinecraftServerFleet
metadata:
  name: minecraft-server-fleet
  namespace: apps
spec:
  clusterRef:
    name: minecraft-cluster
  replicas: 1
  template:
    spec:
      clusterRef:
        name: minecraft-cluster
      tags:
        - lobby
        - vanilla
      version:
        channel: Paper
        name: "1.20.4"
      config: {}
